# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d32b98dd75eab039b2ae24b42d2652e0"
application_url = "https://example.com"
embedded = true
name = "Quote Proxy"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_draft_orders,read_draft_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-04"
