# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2e4b25b7544464a6627d9c679588db4"
name = "Custom Magnets Quote Proxy"
application_url = "https://cm-quote-proxy.onrender.com"
embedded = false

[app_proxy]
url = "https://cm-quote-proxy.onrender.com"
subpath = "quote-proxy"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_draft_orders,read_products,write_price_rules"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://cm-quote-proxy.onrender.com" ]

[webhooks]
api_version = "2026-04"
