# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87194a7ce04446871fe86504fa594378"
name = "Sweets Quote Proxy"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_draft_orders,write_draft_orders,read_inventory,write_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"
